/*
Name: Avni Soni
Roll No:-4006
Batch:-P10
Problem statement:-Write a program in C++ or java to implement SHA1 algorithm using libraries (API)
*/
//------------------------------------------------------------

import java.math.BigInteger; 
import java.security.MessageDigest; 
import java.security.NoSuchAlgorithmException; 
import java.util.Scanner;
  
public class SHA1
{ 
    public static String encryptThisString(String input) 
    { 
        try
        { 
            MessageDigest md = MessageDigest.getInstance("SHA-1"); 
            byte[] messageDigest = md.digest(input.getBytes());         // getBytes returns corresponding encoding of string
                                                                        // e.g ASTHA GFG -> 658384726532717071

            BigInteger no = new BigInteger(1, messageDigest); 

            String hashtext = no.toString(16); 

            while (hashtext.length() < 32) 
            { 
                hashtext = "0" + hashtext; 
            } 
            return hashtext; 
        }  

        catch (NoSuchAlgorithmException e) 
        { 
            throw new RuntimeException(e); 
        } 
    } 
    public static void main(String args[]) throws NoSuchAlgorithmException 
    { 
  
        Scanner input=new Scanner(System.in);
        System.out.println("HashCode Generated by SHA-1 for: "); 
 		String s1=input.next(); 
         
        System.out.println("\n" + s1 + " : " + encryptThisString(s1)); 
    } 
} 

/*
Output:
a3-402-09@a3-402-09:~/Desktop$ javac SHA1.java
a3-402-09@a3-402-09:~/Desktop$ java SHA1
HashCode Generated by SHA-1 for: 
Prajakta

Prajakta : a45b9169f696181ef025bcb66bab99de63d8e5e2

*/
